RSS-ECOMM-2_09-10 registration page implementation/ Input Validation
makarovaiuliia/kickflip pull request #10
Opened 2024-05-13 10:28 UTC by SvetaIlina

## Overview
Implement client-side validation for all required fields in the registration form, such as email, password, first name, last name, date of birth, and address fields (e.g., street, city, postal code, and country) for proper use with CommerceTools.

**What has been done:**
- Implement client-side validation for all required fields in the registration form using
- Display clear and user-friendly error messages indicating any validation issues, such as an improperly formatted email address, a weak password, or incomplete address information.

**Issue(s) closed:**
- [SS-ECOMM-2_09](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/eCommerce-Application/Sprints/Sprint2/RSS-ECOMM-2_09.md)
- [RSS-ECOMM-2_10](https://github.com/rolling-scopes-school/tasks/blob/master/tasks/eCommerce-Application/Sprints/Sprint2/RSS-ECOMM-2_10.md)

## Type of Change
- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Screenshots
![image](https://github.com/makarovaiuliia/kickflip/assets/139857261/43b0b12f-de97-4bb0-8844-8612078cc145)

## Checklist:
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Reviewer Checklist:
- [ ] The code follows the style guidelines of this project.
- [ ] The code is readable and well-commented where necessary.
- [ ] All tests are passing.
- [ ] The changes are well-documented and easy to understand.

2024-05-13 15:09 UTC, makarovaiuliia requested changes

2024-05-13 15:09 UTC, makarovaiuliia commented on kickFlip-project/src/components/form/form.css
> +.reg-form {
Пропустила тут пустую линию

2024-05-13 15:09 UTC, makarovaiuliia commented on kickFlip-project/src/components/form/registrationForm/regForm.tsx
> +    addres: CustomerAdress;
addres -> address
customerAdress -> customerAddress

2024-05-13 15:09 UTC, makarovaiuliia commented on kickFlip-project/src/components/form/registrationForm/regForm.tsx
> +        console.log(data);
console.log лучше убирать перед пушем)

2024-05-13 15:09 UTC, makarovaiuliia commented on kickFlip-project/src/components/form/registrationForm/regForm.tsx
> +type CustomerAdress = { streetName: string; streetNumber: string; city: string; postalCode: string; country: string };
address

2024-05-13 15:09 UTC, makarovaiuliia commented on kickFlip-project/src/pages/registration/regPage.css
> +.regPage-wrapper {
Надо решить, будем мы использовать кебаб или камель кейс, лучше их не мешать

2024-05-13 15:09 UTC, makarovaiuliia commented on kickFlip-project/src/types/type.ts
> +export enum ErrorMessage {
Очень мне нравится использовать отдельный объект для сообщений об ошибках, круто!

2024-05-13 15:10 UTC, makarovaiuliia commented
У страницы логина вроде была обводка, может тут тоже ее оставим?

2024-05-13 15:44 UTC, SvetaIlina commented
> У страницы логина вроде была обводка, может тут тоже ее оставим?

в макете у большой формы не было бордера, но мы конечно можем сделать: 
1 вариант
![image](https://github.com/makarovaiuliia/kickflip/assets/139857261/e7500c7f-c57f-458b-9eab-a545e9887ff5)
2 вариант
![image](https://github.com/makarovaiuliia/kickflip/assets/139857261/0aab9f8d-5cd8-4470-9d8c-f7f8b8b849e1)

2024-05-13 15:45 UTC, SvetaIlina commented on kickFlip-project/src/pages/registration/regPage.css
> +.regPage-wrapper {
давай наверное кебаб)

2024-05-13 15:45 UTC, SvetaIlina commented on kickFlip-project/src/components/form/registrationForm/regForm.tsx
> +type CustomerAdress = { streetName: string; streetNumber: string; city: string; postalCode: string; country: string };
поправила

2024-05-13 15:46 UTC, SvetaIlina commented on kickFlip-project/src/components/form/registrationForm/regForm.tsx
> +        console.log(data);
оки, просто висел для наглядности возвращаемых данных

2024-05-13 15:46 UTC, SvetaIlina commented on kickFlip-project/src/components/form/registrationForm/regForm.tsx
> +    addres: CustomerAdress;
поправила, спасибо! я и не заметила...

2024-05-13 15:47 UTC, SvetaIlina commented on kickFlip-project/src/components/form/form.css
> +.reg-form {
странно, что притиер не  отработал, зато ты глазастая)))

2024-05-13 16:25 UTC, makarovaiuliia commented
Вариант 1 мне нравится)

2024-05-13 16:35 UTC, makarovaiuliia requested changes
Надо будет чуть поправить валидацию. Нужно сделать поля обязательные и необязательные - обязательные имя, фамилия, пароль и имейл, а остальное необязательно, то есть валидировать надо только то, что заполнено, если поле необязательно)

2024-05-13 16:40 UTC, SvetaIlina commented
> Надо будет чуть поправить валидацию. Нужно сделать поля обязательные и необязательные - обязательные имя, фамилия, пароль и имейл, а остальное необязательно, то есть валидировать надо только то, что заполнено, если поле необязательно)

Ну это для аптеки они необязательные, а по таске они все обязательные и с валидацией должны быть

2024-05-14 07:30 UTC, makarovaiuliia approved these changes
Можно мерджить

2024-05-14 08:34 UTC, merged