Rss ecomm 4 07 08 detailed product page implementation
makarovaiuliia/kickflip pull request #104
Opened 2024-06-14 20:03 UTC by Pavel-Kuvshinov

## Overview
Please provide a brief summary of what this pull request accomplishes. Include the motivation behind these changes and the impact they aim to have on the project.

**What has been done:**
- Describe the key changes made in this pull request.

**Why this has been done:**
- Explain the reason these changes are necessary.

**Issue(s) closed:**
- Mention the related issue(s) this pull request closes using the issue number (e.g., `Closes RSS-ECOMM-1_21: Create a pull request template`).

## Type of Change
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Problem Areas
- Describe any parts of the project that were tricky or particularly challenging. This will help reviewers understand where to pay more attention.

## What Reviewers Should Know
- Highlight any specific areas you think reviewers should focus on. 
- Mention if this pull request depends on other pull requests or if it should be merged in a specific order.

## Testing
**Describe the tests that have been added or modified:**
- Detail new tests that have been added to the suite.
- Mention modifications to existing tests.

**Testing instructions:**
- Provide instructions on how to test this pull request.
- Include tips on what to look for and any setup steps if necessary.

## Additional Information
- Include any other information that might be useful for reviewers.

## Screenshots
If applicable, add screenshots to help explain your changes.

## Checklist:
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Reviewer Checklist:
- [ ] The code follows the style guidelines of this project.
- [ ] The code is readable and well-commented where necessary.
- [ ] All tests are passing.
- [ ] The changes are well-documented and easy to understand.

### Final step
Before you submit your pull request, please ensure you have completed everything in the above checklist and delete any sections that are not applicable.

2024-06-15 08:11 UTC, makarovaiuliia requested changes
Небольшие комменты по коду

2024-06-15 08:11 UTC, makarovaiuliia commented on kickFlip-project/src/pages/product/productPage.tsx
> +    const [cartData, setCartData] = useState<CartResponse | null>();
Зачем мы это делаем, если у нас есть данные корзины в сторе? и мы их можем достать через const itemsInCart = useSelector(getCartItems);

2024-06-15 08:11 UTC, makarovaiuliia commented on kickFlip-project/src/pages/product/productPage.tsx
> +        const fetchCartItems = async () => {
Запрос не нужен, если тебе нужны только данные о том, что есть в корзине

2024-06-15 08:11 UTC, makarovaiuliia commented on kickFlip-project/src/components/product/productDetails/productDetailsContainer.tsx
> +            setCartData(newCart);
вот от этого тоже можно будет избавится

2024-06-15 08:11 UTC, makarovaiuliia commented on kickFlip-project/src/components/product/productDetails/productDetailsContainer.tsx
> +            dispatch(setCart(newCart));
Вот это не понимаю зачем в компоненте - если после updateCart нужно поставить новые данные корзины, то делать это нужно в слайсе в ExtraReducers

2024-06-15 18:50 UTC, Pavel-Kuvshinov commented on kickFlip-project/src/pages/product/productPage.tsx
> +    const [cartData, setCartData] = useState<CartResponse | null>();
Исправил

2024-06-15 18:50 UTC, Pavel-Kuvshinov commented on kickFlip-project/src/pages/product/productPage.tsx
> +        const fetchCartItems = async () => {
Исправил

2024-06-15 18:51 UTC, Pavel-Kuvshinov commented on kickFlip-project/src/components/product/productDetails/productDetailsContainer.tsx
> +            setCartData(newCart);
Исправил

2024-06-16 06:20 UTC, Pavel-Kuvshinov commented on kickFlip-project/src/components/product/productDetails/productDetailsContainer.tsx
> +            dispatch(setCart(newCart));
Исправил

2024-06-17 07:16 UTC, makarovaiuliia approved these changes

2024-06-17 07:38 UTC, merged