feat: RSS-ECOMM-2-08-16-17-18-19-20-21 Add page navigation with basic routing.
makarovaiuliia/kickflip pull request #18
Opened 2024-05-15 21:01 UTC by Pavel-Kuvshinov

## Overview
Please provide a brief summary of what this pull request accomplishes. Include the motivation behind these changes and the impact they aim to have on the project.

**What has been done:**
- Describe the key changes made in this pull request.

**Why this has been done:**
- Explain the reason these changes are necessary.

**Issue(s) closed:**
- Mention the related issue(s) this pull request closes using the issue number (e.g., `Closes RSS-ECOMM-1_21: Create a pull request template`).

## Type of Change
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Problem Areas
- Describe any parts of the project that were tricky or particularly challenging. This will help reviewers understand where to pay more attention.

## What Reviewers Should Know
- Highlight any specific areas you think reviewers should focus on. 
- Mention if this pull request depends on other pull requests or if it should be merged in a specific order.

## Testing
**Describe the tests that have been added or modified:**
- Detail new tests that have been added to the suite.
- Mention modifications to existing tests.

**Testing instructions:**
- Provide instructions on how to test this pull request.
- Include tips on what to look for and any setup steps if necessary.

## Additional Information
- Include any other information that might be useful for reviewers.

## Screenshots
If applicable, add screenshots to help explain your changes.

## Checklist:
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Reviewer Checklist:
- [ ] The code follows the style guidelines of this project.
- [ ] The code is readable and well-commented where necessary.
- [ ] All tests are passing.
- [ ] The changes are well-documented and easy to understand.

### Final step
Before you submit your pull request, please ensure you have completed everything in the above checklist and delete any sections that are not applicable.

2024-05-16 07:58 UTC, makarovaiuliia requested changes
Оставила комментарии к коду) Очень большая работа, ты огромный молодец! Все работает, но надо чуть поправить в некоторых местах)

2024-05-16 07:58 UTC, makarovaiuliia commented on kickFlip-project/src/components/app/app.tsx
> +            <Route path="/" element={<Page />}>
Можешь, пожалуйста, рассказать, как это работает? Почему нельзя написать вот так:
``` tsx
<Routes>
        <Route path='/' element={<HomePage />} />
...
</ Routes>
```
Я просто не очень пока понимаю, зачем мы ведем на элемент page? Это у них в доке так?

2024-05-16 07:58 UTC, makarovaiuliia commented on kickFlip-project/src/pages/login/loginPage.tsx
> +        </>
Давай вот это обернем в компонент, так как он повторяется как минимум два раза
```tsx
export default function SomeElement(props) {
    return (
        <>
            <div className="question">
                <p className="question-text">props.question</p>
            </div>
            <Link className="some-button" to={props.navigation}>
                {props.text}
            </Link>
        </>

```

что-то типа такого. Стили соответсвенно и там, и там будут одинаковые. Плюс я уже предложила немного адаптировать дизайн)

2024-05-16 07:58 UTC, makarovaiuliia commented on kickFlip-project/src/pages/notfoundpage/notfoundPage.tsx
> +            <h1 className="notfound-title">Sorry, we can&apos;t find that page</h1>
that -> this - `Sorry, we can't fint this page`

2024-05-16 07:58 UTC, makarovaiuliia commented on kickFlip-project/src/pages/notfoundpage/notfoundPage.tsx
> +            <p className="notfound-text">But we still have lots for you to discover ~</p>
Мне кажется, что стилистически лучше что-то типа `But we have many more things for you to explore.`, но это уже вкусовщина
Там затесался `~` еще в конце предложения

Плюс думаю, что надо хотя бы до 14px увеличить текст, он плоховато читается и по дизайну смотрится не очень пропорционально

![Screenshot 2024-05-16 at 09 45 45](https://github.com/makarovaiuliia/kickflip/assets/144937274/3b0b7b9c-f187-43fb-a202-b88f2140f3d0)

2024-05-16 07:58 UTC, makarovaiuliia commented on kickFlip-project/src/pages/page.css
> +    font-size: 20px;
У @SvetaIlina вроде бы все в rem, я бы предложила эту практику продолжить)

2024-05-16 07:58 UTC, makarovaiuliia commented on kickFlip-project/src/pages/page.css
> +    /* display: flex;
Комментарии лучше убирать перед коммитом

2024-05-16 07:58 UTC, makarovaiuliia commented on kickFlip-project/src/pages/page.tsx
> +                            <svg
Попробуй все так почитать про тэг `use`: [ссылка](https://stackoverflow.com/questions/55452106/how-to-use-the-whole-svg-with-a-use-tag), будет с ним смотрется более лаконично. Но это на будущее, а тут мне кажется, что можно вставить как `img` и не парится. Тэг use и инлайн мы же используем для того, чтобы в дальнейшем свг как то менять (цвет, например). А лого - это статическая штука, поэтому можно его просто как изображение сделать)

2024-05-16 07:58 UTC, makarovaiuliia commented on kickFlip-project/src/pages/page.tsx
> +                            <Link className="services-nav-link" to="/cart">
Может тут сделаем svg все таки, а не текст. Если смущает стилистически, что будет рядом текст и иконка, то можно попробовать сделать как у озона)

![Screenshot 2024-05-16 at 09 52 52](https://github.com/makarovaiuliia/kickflip/assets/144937274/4f968ce9-289f-444a-93f4-131e9e1afb9c)

2024-05-16 07:58 UTC, makarovaiuliia commented on kickFlip-project/src/pages/products/productsPage.css
> +    height: calc(100vh - 96px);
Если несложно, подпиши плиз, что означает 96

2024-05-16 07:58 UTC, makarovaiuliia commented on kickFlip-project/src/pages/registration/registrationPage.tsx
> +            <div className="reg-page-wrapper ">
Может добавить компонент Layout, который будет давать нам нужные паддинги и может даже задавать сетку сайта. Можно пока не делать это, но в следующем спринте я бы сделала такой компонент и убрала бы эту строчку кода, которая по факту делает отступы) Таким образом у тебя пропадут все `home-wrapper`, `cart-wrapper` и тд)

2024-05-16 07:58 UTC, makarovaiuliia commented on kickFlip-project/src/pages/registration/registrationPage.tsx
> +                <p className="reg-page-question-text">Have an account in Kickflip?</p>
`Already have an account? Log in`

2024-05-16 09:07 UTC, SvetaIlina commented on kickFlip-project/src/pages/login/loginPage.css
> +    }
дублирующийся код

2024-05-16 09:19 UTC, SvetaIlina commented on kickFlip-project/src/components/app/app.tsx
> +                <Route index element={<HomePage />} />
index указывает на корневой маршрут, т.е. "/", поэтому я тоже не очень понимаю, зачем нам Page, и что это вообщзе за страница)

2024-05-16 09:36 UTC, SvetaIlina commented on kickFlip-project/src/pages/page.tsx
> +            <header className="header">
header  я бы вынесла в отдельный компонент, как ты сделал с футером)

2024-05-16 09:47 UTC, SvetaIlina commented on kickFlip-project/src/components/app/app.tsx
> +                <Route index element={<HomePage />} />
я поняла))) Page это родитель для всех остальных и раюотает через Outlet в page.tsx, да?

2024-05-16 10:13 UTC, makarovaiuliia commented on kickFlip-project/src/components/app/app.tsx
> +                <Route index element={<HomePage />} />
аааа, тогда гениально)) Я не знала, что так можно сделать!

2024-05-16 10:14 UTC, makarovaiuliia commented on kickFlip-project/src/components/app/app.tsx
> +            <Route path="/" element={<Page />}>
Тут резолвнули

2024-05-16 12:01 UTC, makarovaiuliia commented on kickFlip-project/src/pages/login/loginPage.css
> +    }
а как это этого избавиться? псевдоэлементам же не дашь общий класс?

2024-05-16 17:34 UTC, Pavel-Kuvshinov commented on kickFlip-project/src/components/app/app.tsx
> +            <Route path="/" element={<Page />}>
В литературе, которую я изучал был данный пример и я решил сделать по аналогии. Суть следующая: Мы имеем базовый layout или страницу или элементы, которые на каждой страницы находятся всегда (в нашем случае это header и footer). Я создал базовую страницу "Page". В ней создал базовую разметку (Header, Footer). И там есть раздел main в котором будет меняться контент (HomePage, SiginPage и т.д.) В данном варианте наверное непонятно из-за названия переменной. В измении исправил.

2024-05-16 18:05 UTC, Pavel-Kuvshinov commented on kickFlip-project/src/pages/notfoundpage/notfoundPage.tsx
> +            <h1 className="notfound-title">Sorry, we can&apos;t find that page</h1>
Я пробовал так но react ругается на одинарную кавычку и предложил проэкранировать...

2024-05-16 18:15 UTC, Pavel-Kuvshinov commented on kickFlip-project/src/pages/notfoundpage/notfoundPage.tsx
> +            <p className="notfound-text">But we still have lots for you to discover ~</p>
Согласен. Исправил.

2024-05-16 18:22 UTC, Pavel-Kuvshinov commented on kickFlip-project/src/pages/page.css
> +    font-size: 20px;
Согласен. Исправил во всем своем коде.

2024-05-16 18:23 UTC, Pavel-Kuvshinov commented on kickFlip-project/src/pages/page.css
> +    /* display: flex;
Забыл удалить. Исправил и удалил все комментарии.

2024-05-16 18:45 UTC, Pavel-Kuvshinov commented on kickFlip-project/src/components/app/app.tsx
> +                <Route index element={<HomePage />} />
В литературе, которую я изучал был данный пример и я решил сделать по аналогии. Суть следующая: Мы имеем базовый layout или страницу или элементы, которые на каждой страницы находятся всегда (в нашем случае это header и footer). Я создал базовую страницу "Page". В ней создал базовую разметку (Header, Footer). И там есть раздел main в котором будет меняться контент (HomePage, SiginPage и т.д.) В данном варианте наверное непонятно из-за названия переменной. В измении исправил.

2024-05-16 18:56 UTC, Pavel-Kuvshinov commented on kickFlip-project/src/pages/login/loginPage.css
> +    }
Исправил.

2024-05-16 18:57 UTC, Pavel-Kuvshinov commented on kickFlip-project/src/pages/products/productsPage.css
> +    height: calc(100vh - 96px);
Высота headera

2024-05-16 19:15 UTC, Pavel-Kuvshinov commented on kickFlip-project/src/pages/registration/registrationPage.tsx
> +            <div className="reg-page-wrapper ">
Надеюсь правильно сделал и верно понял замечание.

2024-05-16 20:33 UTC, Pavel-Kuvshinov commented on kickFlip-project/src/pages/page.tsx
> +            <header className="header">
Исправил

2024-05-16 20:34 UTC, Pavel-Kuvshinov commented on kickFlip-project/src/pages/registration/registrationPage.tsx
> +                <p className="reg-page-question-text">Have an account in Kickflip?</p>
Исправил

2024-05-16 20:53 UTC, Pavel-Kuvshinov commented on kickFlip-project/src/pages/page.tsx
> +                            <svg
Вставил как img

2024-05-16 22:24 UTC, Pavel-Kuvshinov commented on kickFlip-project/src/pages/page.tsx
> +                            <Link className="services-nav-link" to="/cart">
Исправил + учел предыдущее замечание по svg. Но далось это не просто.

2024-05-17 07:43 UTC, makarovaiuliia commented on kickFlip-project/src/pages/notfoundpage/notfoundPage.tsx
> +            <h1 className="notfound-title">Sorry, we can&apos;t find that page</h1>
Экранировать - это ок. Я поменяла that на this

2024-05-17 07:45 UTC, makarovaiuliia commented on kickFlip-project/src/pages/products/productsPage.css
> +    height: calc(100vh - 96px);
Лучше прямо комментарием в коде отметить, чтоб потом мы эту информацию не забыли

2024-05-17 07:45 UTC, makarovaiuliia commented on kickFlip-project/src/pages/registration/registrationPage.tsx
> +            <div className="reg-page-wrapper ">
Гляну

2024-05-17 07:46 UTC, makarovaiuliia commented on kickFlip-project/src/components/app/app.tsx
> +                <Route index element={<HomePage />} />
Супер, отличное решение!

2024-05-17 09:39 UTC, makarovaiuliia reviewed
Все отлично! Один коммент по коду и один по стайлингу был в дискорде. Я предалгаю тут сделать одинаковый стайл - размер шрифта, вес шрифта (я бы сделала чуть меньще) и подчеркнуть ссылку обязательно
![image](https://github.com/makarovaiuliia/kickflip/assets/144937274/fb74405a-57cc-4442-8dec-5a80a2e7631a)

2024-05-17 09:39 UTC, makarovaiuliia commented on kickFlip-project/src/pages/login/loginPage.tsx
> +        </>
Я бы тут сделала название компонента более универсальным, может так - `AuthRedirectPrompt `

2024-05-17 10:48 UTC, SvetaIlina commented on kickFlip-project/src/types/types.ts
спасибо за четкие названия)

2024-05-17 10:50 UTC, makarovaiuliia commented on kickFlip-project/src/pages/registration/registrationPage.tsx
> +            <div className="reg-page-wrapper ">
Не, я немного не то имела в виду

2024-05-17 10:51 UTC, makarovaiuliia commented
Короче еще есть проблема с layout я ее пропустила, будем править

2024-05-17 10:52 UTC, makarovaiuliia commented on kickFlip-project/src/pages/registration/registrationPage.tsx
> +            <div className="reg-page-wrapper ">
Ты просто дал другое название компоненту Page, а я хотела отдельный компонент для контента, то есть то, что находится между header и footer

2024-05-17 10:54 UTC, makarovaiuliia commented on kickFlip-project/src/pages/registration/registrationPage.tsx
> +            <div className="reg-page-wrapper ">
![Screenshot 2024-05-17 at 12 53 49](https://github.com/makarovaiuliia/kickflip/assets/144937274/b2512ca7-981c-431e-b2ff-79a417f5b20b)

У тебя на каждую страницу есть вот такой класс, это оч большое повторение, это можно вынести в отдельный компонент

2024-05-17 10:56 UTC, SvetaIlina commented on kickFlip-project/src/components/header/header.tsx
классная идея с актив классами)

2024-05-17 10:56 UTC, SvetaIlina approved these changes

2024-05-17 10:57 UTC, makarovaiuliia commented on kickFlip-project/src/pages/registration/registrationPage.tsx
> +            <div className="reg-page-wrapper ">
либо как временное решение можно сделать один класс на всех

2024-05-17 11:03 UTC, makarovaiuliia commented on kickFlip-project/src/pages/registration/registrationPage.tsx
> +            <div className="reg-page-wrapper ">
Переносим на другой спринт

2024-05-17 11:03 UTC, makarovaiuliia approved these changes

2024-05-17 11:04 UTC, merged